version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
  web:
    build: ./database
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
#    networks:
#      my_net:
#        ipv4_address: 172.26.1.1
  s:
    build: ./service
    restart: always
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    depends_on:
      - web
#    networks:
#      my_net:
#        ipv4_address: 172.26.1.2
        
